### ISSUE TITLE
How to preview ebook as pdf in application

### ISSUE THREAD

**Issue by PawanmSpaceo** [cikpis/GoogleBooks#1]
How to preview/download ebook as pdf in application?

**Comment by carmelogallo** [comment]
Sorry but this is not implemented yet. I’ll keep you posted.

**Comment by PawanmSpaceo** [comment]
Any idea how to do that?

**Comment by carmelogallo** [comment]
I guess you can check online about it. Someone must have achieved what you are looking for.

**Comment by carmelogallo** [comment]
Here it is https://stackoverflow.com/questions/18097841/convert-epub-to-pdf-ios

**Comment by PawanmSpaceo** [comment]
I getting download file of .acsm format

**Comment by PawanmSpaceo** [comment]
Ok no worries thanks for your support

**Comment by carmelogallo** [comment]
No problem :)
